library(edgeR)
library(DESeq2)
library(limma)
library(Biobase)
library(edgeR)
library(limma)
library(Glimma)
library(gplots)
library("org.Mm.eg.db")
library(RColorBrewer)
library(gplots)
library(knitr)
library(calibrate)
library(pheatmap)
library(RColorBrewer)
library(gProfileR)
library("ggplot2")
library("ggdendro")
library("reshape2")
library("grid")
library("limma")
library("MeSH.Xtr.eg.db")
library("dplyr")
library("ggplot2")
library("PoiClaClu")


seqdata <- read.table("count_matrixH.tabular") 
#removing first columns fro the uploaded file
countdata <- seqdata[,-(1)] 
rownames(countdata) <- seqdata[,1]
head(countdata)